---

- name: Make blackbox dir
  file:
    path: /home/{{ admin_user }}/config-blackbox
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
  when: blackbox_exporter_enabled | bool

- name: Copy blackbox exporter config
  template:
    src: "{{ role_path }}/templates/config.yml.blackbox.j2"
    dest: /home/{{ admin_user }}/config-blackbox/config.yml
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
    mode: 0644
  when: blackbox_exporter_enabled | bool
