---

- name: Include debian installs
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure cron jobs
  include_tasks: cron.yml
  when: cron_updater | bool

- name: Install pip3 packages
  pip:
    name: "{{ pippkgs }}"
    executable: pip3
    state: present
  vars:
    pippkgs:
      - pip
      - docker

- name: Create data directory
  file:
    path: "/home/{{ admin_user }}/data"
    mode: '0755'
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"

- name: Create cert directory
  file:
    path: /home/{{ admin_user }}/cert
    mode: '0600'
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"

- name: Prep tasks
  include_tasks: prep.yml
  when: not node_type == 'citizen'
  tags:
    - update-configs

- name: Include nginx conf files
  include_tasks: nginx.yml
  when: reverse_proxy_type == 'nginx'
  tags:
    - update-configs

- name: Configure exporters
  include_tasks: exporters.yml
  when: prometheus_enable | bool

- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: Start node application via docker-compose
  args:
    chdir: "/home/{{ admin_user }}"
  shell: docker-compose up -d

- name: Wait for port 9000 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9000
    delay: 10
