- name: enable docker service
  systemd:
    name: docker
    enabled: yes
    state: started


- name: enable prep service
  systemd:
    name: prep
    enabled: yes
    state: started

#- name: Start node application via docker-compose
#  docker_compose:
#    project_src: /home/icon
#    state: present

- name: Wait for port 9000 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9000
    delay: 10

- name: Wait on node for application to come up and sync
  script: "{{ role_path }}/files/wait-for-sync.sh"

#- name: Stop node application via docker-compose
#  docker_compose:
#    project_src: /home/icon
#    stopped: yes

- name: stop
  service:
    name: prep
    state: stopped

# TODO: fix logic for grabbing ip
- name: Move db files to new IP address
  command: mv db_{{ public_ip }}:7100_icon_dex db_{{ main_ip }}:7100_icon_dex
  become: yes
  when: main_ip is defined and public_ip | default(0.0.0.0) != main_ip
  args:
    chdir: "/home/icon/data/icon/.storage"
