---

#- name: Enable and start prep service
#  systemd:
#    name: prep
#    enabled: yes
#    state: started
#  notify:
#    - systemctl daemon-reload
#  tags:
#    - "service-start"

- name: Start node application via docker-compose
  docker_compose:
    project_src: /home/icon
    state: present
  tags:
    - service-start

- name: Wait for port 9000 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9000
    delay: 10
  tags:
    - service-start

- name: Put sync script on host
  template:
    src: "{{ role_path }}/templates/wait-for-sync.sh"
    dest: /home/icon/wait-for-sync.sh
    owner: icon
    group: icon
    mode: 0644

- name: Changing perm of "/home/icon/wait-for-sync.sh", adding "+x"
  file: dest=/home/icon/wait-for-sync.sh mode=a+x

- name: Run final sync and tx
  shell: cd /home/icon; nohup wait-for-sync.sh > wait-for-sync.log &
  become: true
