version: 2

jobs:
  test:
    docker:
      - image: insightinfrastructure/icon-ci:v0.5.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: Molecule tests
          command: molecule test
