version: '3.7'
services:

  nginx:
    image: 'nginx:1.17.3'
    container_name: 'nginx'
    depends_on:
      - prep
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/access_lists/:/etc/nginx/access_lists/
      - ./nginx/log/:/var/log/nginx/
    ports:
      - 9000:9000
      - 7100:7100
    external_links:
      - prep
    restart: always

  prep:
    image: ${PREP_DOCKER_TAG}

    container_name: prep-${NETWORK_NAME}
    environment:
#      SERVICE: ${NETWORK_NAME}
      NETWORK_ENV: ${NETWORK_ENV}
#      ENDPOINT_URL: ${ENDPOINT_URL}
      PRIVATE_KEY_FILENAME: ${PRIVATE_KEY_FILENAME}
      PRIVATE_PASSWORD: ${PRIVATE_PASSWORD}
      
      LOOPCHAIN_LOG_LEVEL: "DEBUG"
      ICON_LOG_LEVEL: "DEBUG"
      FASTEST_START: ${FASTEST_START}
      CERT_PATH: "/cert"
      
    cap_add:
      - SYS_TIME
    volumes:
      - ./data:/data
      - ./cert:/cert
    expose:
      - '9000'
      - '7100'
    restart: on-failure

  node-exporter:
    image: bitnami/node-exporter:latest
    ports:
      - 9100:9100
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    depends_on:
      - prep

  blackbox-exporter:
    image: bitnami/blackbox-exporter:latest
    ports:
      - 9115:9115
    volumes:
      - ./config-blackbox:/opt/bitnami/blackbox-exporter/conf
    restart: always
    # command: --config.file=/config/blackbox.yml
    depends_on:
      - prep

  nginx-exporter-jsonrpc:
    image: bitnami/nginx-exporter:latest
    ports:
      - 9113:9113
    restart: always
    depends_on:
      - prep
    entrypoint:
    - /usr/bin/exporter
    - -nginx.scrape-uri
    - http://nginx:9000/metrics

  cadvisor:
    image: google/cadvisor:latest
    privileged: true
    stdin_open: true

    container_name: cadvisor
    ports:
    - 8080:8080/tcp
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: "--enable_load_reader=true"
    depends_on:
      - prep
